/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import bbdd.DAOCarritos;
import bbdd.DAOProductos;
import bbdd.DAOUsuarios;
import entidades.Carrito;
import entidades.InfoCarritoDTO;
import entidades.Usuario;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author Raúl
 */
public class VentanaCarrito extends javax.swing.JFrame {

    private Usuario usuario;
    private Carrito carrito;

    private final DAOCarritos daoCarrito = new DAOCarritos();

    /**
     * Creates new form Carrito
     */
    public VentanaCarrito(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(null);
        textoCarrito.setText("Carrito de  " + usuario.getNombre());
        panelcarrito.setLayout(new GridLayout(0, 5, 10, 10));
        cargarCarrito();
    }

    public VentanaCarrito() {
        this(null);
    }

    private void cargarCarrito() {
        panelcarrito.removeAll();

        carrito = daoCarrito.obtenerOCrearCarrito(usuario.getId());

        List<InfoCarritoDTO> productosInfo = daoCarrito.verCarrito(usuario.getId());

        if (productosInfo == null || productosInfo.isEmpty()) {
            JLabel labelVacio = new JLabel("El carrito está vacío.");
            labelVacio.setHorizontalAlignment(SwingConstants.CENTER);
            panelcarrito.add(labelVacio);
        } else {
            for (InfoCarritoDTO producto : productosInfo) {
                JPanel panel = new JPanel();
                panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                panel.setPreferredSize(new Dimension(150, 200));
                panel.setBorder(BorderFactory.createLineBorder(Color.GRAY));

                ImageIcon imagen = new ImageIcon(getClass().getResource("/img/" + producto.getNombreProducto() + ".jpg"));
                Image imgproducto = imagen.getImage().getScaledInstance(120, 100, Image.SCALE_SMOOTH);
                JLabel Imagen = new JLabel(new ImageIcon(imgproducto));
                Imagen.setPreferredSize(new Dimension(120, 100));
                Imagen.setAlignmentX(Component.CENTER_ALIGNMENT);

                JLabel Nombre = new JLabel(producto.getNombreProducto(), SwingConstants.CENTER);
                JLabel Precio = new JLabel(String.format("%.2f €", producto.getPrecioUnidad(), SwingConstants.CENTER));
                JLabel Cantidad = new JLabel("Cantidad: " + producto.getCantidad(), SwingConstants.CENTER);
                Nombre.setAlignmentX(Component.CENTER_ALIGNMENT);
                Precio.setAlignmentX(Component.CENTER_ALIGNMENT);
                Cantidad.setAlignmentX(Component.CENTER_ALIGNMENT);

                JButton Eliminar = new JButton("Eliminar del carrito");
                Eliminar.setAlignmentX(Component.CENTER_ALIGNMENT);
                Eliminar.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //daoCarrito.eliminarProducto();
                        cargarCarrito();
                    }

                });

                panel.add(Imagen);

                panel.add(Nombre);

                panel.add(Cantidad);

                panel.add(Precio);

                panel.add(Eliminar);

                panelcarrito.add(panel);
            }
            panelcarrito.revalidate();
            panelcarrito.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoCarrito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelcarrito = new javax.swing.JPanel();
        botonComprar = new javax.swing.JButton();
        vaciarCarrito = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        textoCarrito.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        textoCarrito.setText("jLabel1");
        jPanel1.add(textoCarrito);
        textoCarrito.setBounds(40, 20, 500, 60);

        panelcarrito.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelcarritoLayout = new javax.swing.GroupLayout(panelcarrito);
        panelcarrito.setLayout(panelcarritoLayout);
        panelcarritoLayout.setHorizontalGroup(
            panelcarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        panelcarritoLayout.setVerticalGroup(
            panelcarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelcarrito);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 500, 350);

        botonComprar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonComprar.setText("COMPRAR");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });
        jPanel1.add(botonComprar);
        botonComprar.setBounds(580, 310, 120, 23);

        vaciarCarrito.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        vaciarCarrito.setText("Vaciar carrito");
        vaciarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(vaciarCarrito);
        vaciarCarrito.setBounds(570, 190, 140, 28);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver);
        Volver.setBounds(600, 30, 75, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        if (carrito == null) {
            JOptionPane.showMessageDialog(this, "No tienes carrito, subnormal.");
            return;
        }
        List<InfoCarritoDTO> productosInfo = daoCarrito.verCarrito(usuario.getId());
        if (productosInfo == null || productosInfo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío, gilipollas.");
            return;
        }

        //daoCarrito.vaciarCarrito(carrito.getId());
        JOptionPane.showMessageDialog(this, "Compra realizada");

        // Crea el nuevo carrito automáticamente con tu método robusto
        carrito = daoCarrito.obtenerOCrearCarrito(usuario.getId());

        cargarCarrito();
    }//GEN-LAST:event_botonComprarActionPerformed

    private void vaciarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarCarritoActionPerformed
        //daoCarrito.vaciarCarrito(carrito);
        cargarCarrito();
    }//GEN-LAST:event_vaciarCarritoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Principal principal = new Principal(usuario);
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton botonComprar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelcarrito;
    private javax.swing.JLabel textoCarrito;
    private javax.swing.JButton vaciarCarrito;
    // End of variables declaration//GEN-END:variables

}
